name: 'Test'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  changes:
    name: 'Test'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get changed dirs
      uses: rodrigodealer/last-changed-dir@v1
      with:
        forbidden: '["other"]'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cat file
      run: cat $HOME/dirs.json
